services:
  app:
    build: .
    container_name: library-api
    volumes:
      - ./src:/app/src
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      - postgresql_container
    env_file:
      - .env

  postgresql_container:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
