"""Add all tables

Revision ID: 3f6b3fac956a
Revises: 0926f625ec00
Create Date: 2025-06-14 23:00:24.947488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6b3fac956a'
down_revision: Union[str, None] = '0926f625ec00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_uuid'), 'books', ['uuid'], unique=False)
    op.create_table('librarians',
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_librarians_email'), 'librarians', ['email'], unique=True)
    op.create_index(op.f('ix_librarians_id'), 'librarians', ['id'], unique=False)
    op.create_table('readers',
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readers_email'), 'readers', ['email'], unique=True)
    op.create_index(op.f('ix_readers_id'), 'readers', ['id'], unique=False)
    op.create_table('tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_tokens_refresh_token'), 'tokens', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_tokens_uuid'), 'tokens', ['uuid'], unique=False)
    op.create_table('borrowedbooks',
    sa.Column('book_uuid', sa.UUID(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['book_uuid'], ['books.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['librarians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_borrowedbooks_uuid'), 'borrowedbooks', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrowedbooks_uuid'), table_name='borrowedbooks')
    op.drop_table('borrowedbooks')
    op.drop_index(op.f('ix_tokens_uuid'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_refresh_token'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_readers_id'), table_name='readers')
    op.drop_index(op.f('ix_readers_email'), table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_librarians_id'), table_name='librarians')
    op.drop_index(op.f('ix_librarians_email'), table_name='librarians')
    op.drop_table('librarians')
    op.drop_index(op.f('ix_books_uuid'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
